apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmap-pvc
  namespace: openmap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 60Gi